language: cpp

compiler:
    - gcc

before_install:
    - sudo apt-get install libeigen3-dev libmpfrc++-dev
    - echo $LANG

before_script:
    - mkdir build
    - cd build
    - cmake ../

script:
    - $CXX --version
    - make
